In [30]:
import json
import os

import pandas as pd

# Plot the accuracy

dir = '../data/results/experiments/random_forest_experiment_5'

data_df = pd.read_csv(os.path.join(dir, 'data.csv')).drop(columns=['Unnamed: 0'])

with open(os.path.join(dir, 'config.json')) as f:
    config = json.load(f)

data_df

    accuracy    recall  f1_score  mean_cv_score param  n_clusters  run
0   0.995825  0.994732  0.995474       0.993737  rsrq           2    0
1   0.990999  0.990455  0.990698       0.985002  rsrq           3    0
2   0.990849  0.989457  0.989484       0.977950  rsrq           4    0
3   0.979290  0.974853  0.974499       0.964074  rsrq           5    0
4   0.981172  0.975823  0.975910       0.969038  rsrq           6    0
5   0.973862  0.967753  0.969195       0.938858  rsrq           7    0
6   0.971406  0.963687  0.964112       0.945206  rsrq           8    0
7   0.966358  0.965630  0.966228       0.933982  rsrq           9    0
8   0.968803  0.963208  0.965343       0.919461  rsrq          10    0
9   0.964227  0.951907  0.952510       0.916525  rsrq          11    0
10  0.948101  0.932592  0.936399       0.902954  rsrq          12    0
11  0.948771  0.937519  0.940198       0.882954  rsrq          13    0
12  0.954526  0.933252  0.939401       0.878316  rsrq          14    0
13  0.948047  0.908772  0.922812       0.883198  rsrq          15    0
14  0.944670  0.933965  0.936728       0.882034  rsrq          16    0
15  0.940768  0.929178  0.933188       0.880325  rsrq          17    0
16  0.933333  0.921163  0.923584       0.866253  rsrq          18    0
17  0.944192  0.927172  0.934111       0.873509  rsrq          19    0
18  0.927822  0.906746  0.913127       0.837197  rsrq          20    0

In [31]:
res = data_df.groupby('n_clusters')[['accuracy', 'recall', 'f1_score', 'mean_cv_score']].mean().round(3)

In [32]:
res

            accuracy  recall  f1_score  mean_cv_score
n_clusters
2              0.996   0.995     0.995          0.994
3              0.991   0.990     0.991          0.985
4              0.991   0.989     0.989          0.978
5              0.979   0.975     0.974          0.964
6              0.981   0.976     0.976          0.969
7              0.974   0.968     0.969          0.939
8              0.971   0.964     0.964          0.945
9              0.966   0.966     0.966          0.934
10             0.969   0.963     0.965          0.919
11             0.964   0.952     0.953          0.917
12             0.948   0.933     0.936          0.903
13             0.949   0.938     0.940          0.883
14             0.955   0.933     0.939          0.878
15             0.948   0.909     0.923          0.883
16             0.945   0.934     0.937          0.882
17             0.941   0.929     0.933          0.880
18             0.933   0.921     0.924          0.866
19             0.944   0.927     0.934          0.874
20             0.928   0.907     0.913          0.837

In [33]:
for i, row in res.iterrows():
    items = [str(e) for e in row.values.tolist()]
    r = f"{i} & {' & '.join(items)} \\\\ \hline"
    print(r)

2 & 0.996 & 0.995 & 0.995 & 0.994 \\ \hline
3 & 0.991 & 0.99 & 0.991 & 0.985 \\ \hline
4 & 0.991 & 0.989 & 0.989 & 0.978 \\ \hline
5 & 0.979 & 0.975 & 0.974 & 0.964 \\ \hline
6 & 0.981 & 0.976 & 0.976 & 0.969 \\ \hline
7 & 0.974 & 0.968 & 0.969 & 0.939 \\ \hline
8 & 0.971 & 0.964 & 0.964 & 0.945 \\ \hline
9 & 0.966 & 0.966 & 0.966 & 0.934 \\ \hline
10 & 0.969 & 0.963 & 0.965 & 0.919 \\ \hline
11 & 0.964 & 0.952 & 0.953 & 0.917 \\ \hline
12 & 0.948 & 0.933 & 0.936 & 0.903 \\ \hline
13 & 0.949 & 0.938 & 0.94 & 0.883 \\ \hline
14 & 0.955 & 0.933 & 0.939 & 0.878 \\ \hline
15 & 0.948 & 0.909 & 0.923 & 0.883 \\ \hline
16 & 0.945 & 0.934 & 0.937 & 0.882 \\ \hline
17 & 0.941 & 0.929 & 0.933 & 0.88 \\ \hline
18 & 0.933 & 0.921 & 0.924 & 0.866 \\ \hline
19 & 0.944 & 0.927 & 0.934 & 0.874 \\ \hline
20 & 0.928 & 0.907 & 0.913 & 0.837 \\ \hline